services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment: 
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: somedatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/app_data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: test_app
    depends_on:
      - db 
    environment:
      DATABASE_URL: postgresql://someuser:somepassword@db:5432/somedatabase
    volumes :
      - ./data:/app_data
    ports:
      - "8000:8000"

volumes:
  postgres_data: